### ISSUE TITLE
General Build Discussion

### ISSUE THREAD

**Issue by l-arnold** [DocCyblade/tkl-odoo#11]
Seems worth while to have a "general build" discussion that could lead to opening of full issues.  Perhaps too much gets lost however.

**Comment by l-arnold** [comment]
Not sure we need to "stop/start" Apache and Postgresql always when we do so with OPENERP/Odoo.  I realize it should be "fail safe" but it seems we can get Odoo to Cycle while keeping the other two up and running.  Only exception is if we change the settings in either one (user or site for instance)

In
overlay/etc/init.d/openerp-server

+# Required-Start:  $remote_fs $syslog postgresql apache2
-# Required-Stop:   $remote_fs $syslog      +# Required-Stop:   $remote_fs $syslog postgresql apache2

**Comment by l-arnold** [comment]
Recomend a "Backup" copy of overlay/etc/odoo/openerp-server.conf

As Odoo will totally change it when the database/manager changes the Admin Password.

**Comment by DocCyblade** [comment]
The backup copy is a good idea, make that an issue

I was trying to keep comments compartmentalized so that the subjects don't wonder and we don't have a run away issue.

Dialog like this would be in the build notes for the current version

Testing dialog should only be about the current test, any problems found, open a new issue for it. 

That way issue dialogs are all on the subject of the issue or fixing of an issue. 

I'll change this issue to WIP notes

**Comment by l-arnold** [comment]
Ok.  Will try to avoid overloading this dialog space.

**Comment by DocCyblade** [comment]
No worries !

**Comment by l-arnold** [comment]
Link of General Interest:  Odoo
Releasing Odoo-based projects as Debian packages

Would seem an interesting way to "add modules" perhaps... but I should read the whole post.

https://anybox.fr/blog/releasing-odoo-based-projects-as-debian-packages

**Comment by DocCyblade** [comment]
Packages are the best way, and if they add then with packages that makes things so much easier

**Comment by l-arnold** [comment]
I believe this was proposing "building packages" that become part of the debian repository.  The post weighs a lot of pros and cons on the subject.  NOT THIS PROJECT now I say.

**Comment by JedMeister** [comment]
I hope I'm posting in the right place... I'm just having a bit of a look through the code and will open individual issues here for anything I find worthy of note. I hope that works for you guys.

**Comment by DocCyblade** [comment]
@JedMeister - This is good as any! I am reviewing all the posts. I'll post my response after I review everything.

**Comment by DocCyblade** [comment]
@l-arnold I should have beta 5 (hopefully the last) then RC1 in the next 24-48 hours

**Comment by l-arnold** [comment]
Excellent.  I will try to catch up on other subjects.  Won't work for any l-arnold/merges on my side till Beta 5 jumps.

Let me know if there are any specific tests needed tomorrow.  
Thanks Ken!

**Comment by DocCyblade** [comment]
@l-arnold  I will try and get beta 5 done by the end of today. Keep an eye out for a tagged release.

**Comment by l-arnold** [comment]
Will keep an eye out.  Should be able to build in short order.

**Comment by DocCyblade** [comment]
@l-arnold @JedMeister beta 5 is out. This should be the closest to a RC1. Need to focus on Odoo function make sure things are good. Note: since this is a very large app we may need to note or point out that the server should be a little more beefy than most TKL. I had to bump my VM to from 512MB to 2GB and 2 CPUs for it to be much faster. I am out until this time tomorrow so won't hear from me until then

**Comment by l-arnold** [comment]
Building Full Beta 5 now.  Will report back with run reports.  

Thanks for the hard work Ken!

**Comment by l-arnold** [comment]
I think it will run w/ 512 but I agree that more is better.  I have my "production" (if you can call it that running at 1 gb without jobrunner and 2 gb w/ jobrunner as I have noted.

I pretty much always give to processors to a system so don't have experience on that impact.  Jobrunner wants lots of processors.  Job Runner will go and get data from other systems (Connector platform, so Magento etc).  You can run Connector without that and performance of Odoo is fine.  Connections to Magento are slow is all but that does not really need to be fast unless one has a very active commerce situation.

**Comment by l-arnold** [comment]
@DocCyblade 
So, where besides (main - wkhtmltopdf) do you implement wkhtmltox ?

I am only seeing wkhtmltopdf coming in.

(OK, in MAIN)

If we are pulling wkhtmltox in main I do not believe we should be pulling wkhtmltopdf also.

**Comment by l-arnold** [comment]
Also, I find it a little bit "confusing" to have 2 x files with the name "main".

one in conf.d
one in plan

Is that TKL Standard practice now?
It looks we were moving that way on l-arnold (when we renamed xxx_ odoo_inst_file to 30_main)

**Comment by DocCyblade** [comment]
@l-arnold - main is the default. The one in plan is a list of deb packages, the ones in conf.d is bash scripts to install or edit the install. Multi are used when the config is complicated and very long. See [Gitlab Code](https://github.com/turnkeylinux-apps/gitlab/tree/master/conf.d) as an example. Since I was simplifying I renamed it back to main

**Comment by l-arnold** [comment]
Sounds good.  Was just jumping around thinking was something was in 1 main when it was in the other is all.

Not that complicated really.

**Comment by DocCyblade** [comment]
@l-arnold - As we get close to the final version that may get pulled (hopefully) to the Official TKL repos, I want to start working on a feature list for the next version. Think what you would like to have in future versions of a TKL Odoo appliance. Go ahead and be free with the suggestions. Open a new issue, prefix it with [feature] 

This will start a road map of where we want Odoo TKL to end up.

**Comment by DocCyblade** [comment]
Closing this, let keep the discussion based on the current version being worked. This will keep things organized. Currently put comments on #35
