### ISSUE TITLE
Test Beta 4 - Hotfix 1

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#13]
Log a new issue is you find problems with this build. Use comments in this issue to explain any testing issues that are not a problem maybe a concern. 
- [x] Install 
- [x] See that Odoo is running (should land on the Database manager page
- [x] Change Admin Password in Odoo Database Manager (testing control)
- [x] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [x] Install CRM Module
- [x] Install Online Billing
- [x] Install Sales Management
- [x]  Create a Customer
- [x]  Create a Quotation for the Customer
- [x]  When quotation is saved, Choose Print  (or Email)
- [x]  See that a Formatted Doc Shows up
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
- [x]  Check that Git is applying to opt/openerp/odoo files 
- [x] Check manual stop/start/restart work using `/etc/init.d/openerp-server`
- [x] Check manual stop/start/restart work using `systemctl stop openerp-server.service`
  check the status of the service with `systemctl status openerp-server.service`

**Comment by l-arnold** [comment]
Hot Fix:  Firstboot (no reboot, no services restart etc) Based on HotFix Build

built sample database  (not sure the lag time from first boot (no reboot), as lag was on my side)

wkhtmltox appears to be working

![screenshot 2015-09-30 10 13 47](https://cloud.githubusercontent.com/assets/5673448/10199320/602576da-675d-11e5-9fc4-52d67aa94b4d.png)

**Comment by l-arnold** [comment]
Lots of ways to test some of this.  Quickest is to run "sales management" using "demo data" and print / email one of the created invoices.

**Comment by l-arnold** [comment]
Email not transmitting (to me anyway) out of the box.

**Comment by l-arnold** [comment]
Seems like the service should be stopped now ??  Status seems to show a log as well (interesting it shows the "stop" process that already was issued.

![screenshot 2015-09-30 10 52 55](https://cloud.githubusercontent.com/assets/5673448/10200117/c206d386-6761-11e5-97f2-80cf757532f3.png)

Also Restarted via  "start"  Odoo was responsive 

Will try init.d methods next.

**Comment by l-arnold** [comment]
Cycling well with Services:
See shot w/ Attempted odoo with Service Off.  
![screenshot 2015-09-30 11 00 28](https://cloud.githubusercontent.com/assets/5673448/10200415/87b795c4-6763-11e5-862c-33c46fdca96a.png)

the followed by log with Service On again (and Odoo was responsive immediately afterwards)

![screenshot 2015-09-30 11 01 29](https://cloud.githubusercontent.com/assets/5673448/10200406/69b3c138-6763-11e5-82c4-c0f702fdeea7.png)

**Comment by l-arnold** [comment]
![screenshot 2015-09-30 11 10 16](https://cloud.githubusercontent.com/assets/5673448/10200484/0a772236-6764-11e5-99cd-f6e09bc9a4a6.png)

Git Branch is 8.0 in /opt/openerp/odoo

**Comment by l-arnold** [comment]
SO, I think we have all that except an outgoing Email success.  Likely some setup required in Postfix.  This is where we set up Mail in Odoo.

I did get a "Positive Confirmation" for Localhost being responsive in Odoo so likely now "domain headers" etc that need to get passed to land in my system.

These Screen Shots show the testing and setup paths for Odoo:  Need to send the "Admin Mail" as well as the Server Alias to begin with...  but more for sure.  Odoo config issues mostly.

Where to config Mail Settings:
Alias Domain needs a real domain.

![screenshot 2015-09-30 11 14 11](https://cloud.githubusercontent.com/assets/5673448/10200802/b6c70b40-6765-11e5-92f5-c0e7fe40bd05.png)

Confirmation of Outgoing (here only to Localhost) being functional.  Postfix to the World needs confirmation still.

![screenshot 2015-09-30 11 16 13](https://cloud.githubusercontent.com/assets/5673448/10200807/bf86d4ea-6765-11e5-838b-9147a6743736.png)

User Settings (need to check "technical" to get to Messages next.  Also on the second tab here is where you set up Administrators proper email address.  This is important to set.
![screenshot 2015-09-30 11 16 38](https://cloud.githubusercontent.com/assets/5673448/10200811/c37c64ca-6765-11e5-89f4-5225084cbee0.png)

Log of internal and external messages.

![screenshot 2015-09-30 11 17 15](https://cloud.githubusercontent.com/assets/5673448/10200816/ca3d6c6e-6765-11e5-8792-2d7f95dd9867.png)

the actual Message  (too bad on campaign mail the same info does not come in, but anyway)

![screenshot 2015-09-30 11 17 41](https://cloud.githubusercontent.com/assets/5673448/10200818/d143682e-6765-11e5-8915-813b091b2d5f.png)

**Comment by l-arnold** [comment]
It seems we are good on this.  I am going to Close.

Now I only need this system with all of my Extra-Addons back :)

**Comment by l-arnold** [comment]
BTW,  Very Nice work Ken!

**Comment by l-arnold** [comment]
@

**Comment by l-arnold** [comment]
@DocCyblade   I just re-opened this as it appears that my closing it yesterday kept @jJedmeister from seeing the great work that you had done on this HotFix.

I can't actively Tag him, so not sure if the tag will reach him either.  Do Check.

**Comment by DocCyblade** [comment]
@l-arnold going to close this again, Jeremy should be able to see this even when closed.
