### ISSUE TITLE
plan uses incorrect comment marker

### ISSUE THREAD

**Issue by JedMeister** [DocCyblade/tkl-odoo#14]
I notice that the [plan](https://github.com/DocCyblade/tkl-odoo/blob/434e951ea2081ba07709007e0c60cdcd10e7206f/plan/main) uses `#` for comments. Whilst the plans are just text files, technically they are actually C files. The C pre-processor DOES NOT treat `#` as a comment! You need to enclose comments in `/*` and `*/` e.g. [WordPress appliance](https://github.com/turnkeylinux-apps/wordpress/blob/master/plan/main).

Now what impact it's actually been having I'm not really sure. TBH I would have expected it to be causing errors. But obviously nothing hugely significant. At the very least though I would expected it to stop any packages with comments (starting with `#`) from installing. But I imagine that you would have noticed that too!

**Comment by JedMeister** [comment]
FWIW this is the sed regex I used: `s|# *$||; s|# |/* |; /\/\*/ s/$/ \*\//`

**Comment by DocCyblade** [comment]
@JedMeister I wondered what was the correct way. I found the # works only after the statement. The build does not fail. But good to know what the correct way to comment is. I wanted to comment a little more, group them packages. If you have seen I like well documented files, if not for others sake for my own if I go back 3 months and try to figure out what I was doing!

**Comment by DocCyblade** [comment]
#15 closes this

**Comment by JedMeister** [comment]
:+1:
