### ISSUE TITLE
complete changelog

### ISSUE THREAD

**Issue by JedMeister** [DocCyblade/tkl-odoo#16]
Prior to release the [changelog](https://github.com/DocCyblade/tkl-odoo/blob/dev/changelog) will need to be updated.

An example changelog is [laravel](https://github.com/turnkeylinux-apps/laravel/blob/master/changelog) although you could go into a little more detail if you wanted.

**Comment by DocCyblade** [comment]
I am thinking something like the following, @l-arnold your thoughts?

```
turnkey-laravel-14.0 (1) turnkey; urgency=low

  * Initial release of appliance based of LAPP v14.0

  * Based largely on the great work and help of Landis Arnold (@l-arnold)

    https://github.com/l-arnold/tkl-nomadic-odoo

  * Includes the basic source (GIT) install of Odoo (8.0)

  * Note: Please refer to turnkey-lapp's changelog for changes common to all
    lapp, and please refer to turnkey-core's changelog for changes common to all
    appliances. 

 -- Ken Robinson <ken@robinsonshome.net>  Thu, 1 Oct 2015 04:00:00 -0500
```

**Comment by l-arnold** [comment]
Generally ok.   How about the following: 

turnkey-laravel-14.0 (1) turnkey; urgency=low
- Initial release of appliance based of LAPP v14.0
- Current version Includes the basic source (GIT) install of Odoo (8.0)
- Based largely on the great work and help of Landis Arnold (@l-arnold)
  
  https://github.com/l-arnold/tkl-nomadic-odoo
-  l-arnold version re-integrates this basic source and is extended by several 
   OCA community modules  (Odoo Community Association).
- Note: Please refer to turnkey-lapp's changelog for changes common to all
  lapp, and please refer to turnkey-core's changelog for changes common to all
  appliances. 
  
  -- Ken Robinson ken@robinsonshome.net  Thu, 1 Oct 2015 04:00:00 -0500

**Comment by l-arnold** [comment]
Alternatively @DocCyblade , we could simply have this change log reference both of us as well as @JedMeister  in the last lines and refer to the "alternative buildout" under the l-arnold branch/repository.

**Comment by DocCyblade** [comment]
@JedMeister don't count.( Just kidding! You guidance was :+1:  ) Think he can opt out if he wants. @l-arnold look good to you? I want to be clear your work was the foundation of my work, you baked the cake,  and Jeremy just put the icing on the cake :cake:  :smile: 

```
turnkey-laravel-14.0 (1) turnkey; urgency=low

  * Initial release of appliance based of LAPP v14.0

  * Includes the basic source (GIT) install off Odoo (8.0)

  * Based on the team work of the following community members 
    Landis Arnold (@l-arnold)
    Ken Robinson (@DocCyblade)
    Jeremy Davis (@JedMeister)

    Original build sources
    https://github.com/l-arnold/tkl-nomadic-odoo
    https://github.com/DocCyblade/tkl-odoo

  * Note: Please refer to turnkey-lapp's changelog for changes common to all
    lapp, and please refer to turnkey-core's changelog for changes common to all
    appliances. 

 -- Ken Robinson <ken@robinsonshome.net>  Thu, 1 Oct 2015 04:00:00 -0500
```

**Comment by l-arnold** [comment]
Looks great!

**Comment by DocCyblade** [comment]
Complete - https://github.com/DocCyblade/tkl-odoo/commit/2857f72ca95d13518710bbaf5d29f7f7a075c3e6 closed this
