### ISSUE TITLE
Testing Template

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#2]
Edit this main post for the template.
- [ ] Install 
- [ ] See that Odoo is running (should land on the Database manager page
- [ ] Change Admin Password in Odoo Database Manager (testing control)
- [ ] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [ ] Install CRM Module
- [ ] Install Online Billing
- [ ] Install Sales Management
- [ ]  Create a Customer
- [ ]  Create a Quotation for the Customer
- [ ]  When quotation is saved, Choose Print  (or Email)
- [ ]  See that a Formatted Doc Shows up
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
- [ ]  Check that Git is applying to opt/openerp/odoo files 
- [ ] Check manual stop/start/restart work using `/etc/init.d/openerp-server`
- [ ] Check manual stop/start/restart work using `systemctl stop openerp-server.service`
  check the status of the service with `systemctl status openerp-server.service`

**Comment by DocCyblade** [comment]
Will use some of this for a testing list to test each release. 

Taken from post (https://github.com/l-arnold/tkl-nomadic-odoo/issues/26#issuecomment-143499475)
- [ ] Build the App
- [ ] Install 
- [ ] See that Odoo is running (should land on the Database manager page - URL should be in confconsole I feel)
- [ ] Change Admin Password in Odoo Database Manager (testing control)
- [ ] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [ ] Install CRM Module
- [ ] Install Online Billing
- [ ] Install Sales Management
- [ ]  Create a Customer
- [ ]  Create a Quotation for the Customer
- [ ]  When quotation is saved, Choose Print  (or Email)
- [ ]  See that a Formatted Doc Shows up
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
- [ ]  Check that Git is applying to opt/openerp/odoo files 
- [ ]  Check that various  add ons added in 50-(additional add ons) are showing in settings, module
- [ ]  ideally we should check those specific add ons to see that they install.
- [ ]  base Odoo add ons should install  (deliniate where those go vs outside addons - ie look at the code)
- [ ]  in Shell, test the /etc/init.d/openerp-server  (initialization) commands
   /bin/bash openerp-server stop
   /bin/bash openerp-server start
  /bin/bash openerp-server restart
  -   (make sure system is actually running in browser.  if an issue will return "service unavailable"
  -  best to try some of the -u  -d variables outlined earlier.
  -  worth looking at the actua file to see how it is structured.  Not sure if that is an odoo creation of something of our legacy here to be honest.  (used to have a "softlink" called openero.init that would instagate that file and did not require the /bin/bash call.  That I found convenient.  Might be good to bring back somehow and leave it in /opt/openerp/  folder
- [ ]  
- [ ]  At this point lots of settings need to be made to be sure the system is working on a customized basis. 

Other Tests to perform include migrating Data via "backup and restore" commands in the Odoo Database Manager.  I find this better than tklbam for the time being as tklbam is restoring virutually the full system (including the old git).

Worth moving some data files between machines.  Need to use "whole database option on the restore" command (not the "backup-restore" option)

wkhtmltox:
Need to run this dependency and not wkhtmltopdf debian package.

wkhtmltox (for emails, quotations, reports) is working in my base dev-wip1 branch (same as the jobrunner problem)

Unfortunately, my wkhtmltox is not working on the system that I configured "jobrunners" for in the Magento Connector.  I even reduced the number of workers to 1 (from 4).  running on 1 Gb of Ram.  Will briefly test 2 Gb but expecting it is not actually a Ram issue at this point.

incoming mail (in my docs).  Should not really be an issue in the install.  User needs to config their MX files etc.

ssl:  Also.  I can give you the template of how I install basic ssl with specific certs and not tkl certs

a2ensite odoo-12325  (web console post install).  I highly encourage this being kept in /etc/apached2/sites-available)
(it does not have to be loaded by default but would encourage it on every app personally)

OK,  all for now.

**Comment by DocCyblade** [comment]
Comments on these tests:

Will use some of this for a testing list to test each release. 

Taken from post (https://github.com/l-arnold/tkl-nomadic-odoo/issues/26#issuecomment-143499475)
- [ ] Build the App
  **(Not needed, as we will test pre-build ISO files. However, if we find an issue, it would be good to then do a build on another TKLDev box to rule out a build issue)**
- [ ] Install
  **(The install should come up to a running system, with or without updates, and any other install options)**

**(All the below this line looks good)**
- [ ] See that Odoo is running (should land on the Database manager page - URL should be in confconsole I feel)
- [ ] Change Admin Password in Odoo Database Manager (testing control)
- [ ] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [ ] Install CRM Module
- [ ] Install Online Billing
- [ ] Install Sales Management
- [ ]  Create a Customer
- [ ]  Create a Quotation for the Customer
- [ ]  When quotation is saved, Choose Print  (or Email)
- [ ]  See that a Formatted Doc Shows up

**(All the above this line looks good)**
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
  **(We should have this working out of the box. IT should be very easy as this is based on LAPP and LAPP does have postfix)**
- LA - agreed, 
- [ ]  Check that Git is applying to opt/openerp/odoo files
  **(I guess you mean that the odoo directory is a GIT repo? If so I agree if we will be keeping the git repos)**
- LA - agreed.  It seems we should be keeping the git repos, but perhaps we could make a "first boot" Y/N question for the installer.
- [ ]  Check that various  add ons added in 50-(additional add ons) are showing in settings, module
- [ ]  ideally we should check those specific add ons to see that they install.
- [ ]  base Odoo add ons should install  (deliniate where those go vs outside addons - ie look at the code)
  **(This would be for testing versions that have the core add ons that are decided)**
- LA - Yes.  "Core Add Ons" are quite a large number.  The "optional" add ons are quite few in comparison.  We will look at the list on both sides of that equation.  
- [ ]  in Shell, test the /etc/init.d/openerp-server  (initialization) commands
   /bin/bash openerp-server stop
   /bin/bash openerp-server start
  /bin/bash openerp-server restart
  -   (make sure system is actually running in browser.  if an issue will return "service unavailable"
  -  best to try some of the -u  -d variables outlined earlier.
  -  worth looking at the actual file to see how it is structured.  Not sure if that is an odoo creation of something of our legacy here to be honest.  (used to have a "softlink" called openero.init that would instagate that file and did not require the /bin/bash call.  That I found convenient.  Might be good to bring back somehow and leave it in /opt/openerp/  folder
    **( Testing the control script `openerp-server` is a good idea. However its best to call it from system calls too. Example below. 

``` bash
# These all should stop Odoo
#
#

# Calling the bash script
./etc/init.d/openerp-server stop

# Using the service command
service openerp-server stop 

# Using the systemctl command 
systemctl stop openerp-server.service
```

**Just swap out `stop` with `start` or `restart` for the other commands**
- LA  (Are we clear that the systemctl start stop has a "soft" shutdown process?  I understood from separate git conversation in Connector that "harsh" shutdowns can leave certains jobs "hung".  Not sure if there are other aspects to this.

**(We need to focus on new installs at the moment, once we have a good base install, then finally one with include core add ons, then a good go at documenting imported data would be a good idea. That in it's self will need it's own test matrix.)**
- LA - Agreed
- [ ]  At this point lots of settings need to be made to be sure the system is working on a customized basis. 
- LA - Agreed.  Will require some additional "sed" type configuration to be sure Add-ons Paths are declared properly when a additional module is optionally chosen.

Other Tests to perform include migrating Data via "backup and restore" commands in the Odoo Database Manager.  I find this better than tklbam for the time being as tklbam is restoring virutually the full system (including the old git). 

Worth moving some data files between machines.  Need to use "whole database option on the restore" command (not the "backup-restore" option)

wkhtmltox:
Need to run this dependency and not wkhtmltopdf debian package.

wkhtmltox (for emails, quotations, reports) is working in my base dev-wip1 branch (same as the jobrunner problem)

Unfortunately, my wkhtmltox is not working on the system that I configured "jobrunners" for in the Magento Connector.  I even reduced the number of workers to 1 (from 4).  running on 1 Gb of Ram.  Will briefly test 2 Gb but expecting it is not actually a Ram issue at this point.

incoming mail (in my docs).  Should not really be an issue in the install.  User needs to config their MX files etc.

ssl:  Also.  I can give you the template of how I install basic ssl with specific certs and not tkl certs

a2ensite odoo-12325  (web console post install).  I highly encourage this being kept in /etc/apached2/sites-available)
(it does not have to be loaded by default but would encourage it on every app personally)

OK,  all for now.

**Comment by l-arnold** [comment]
- LA Comments added to post above.

**Comment by DocCyblade** [comment]
Added service stop/start check to template https://github.com/DocCyblade/tkl-odoo/issues/10#issuecomment-144214497

**Comment by l-arnold** [comment]
I guess I could have done that.  Thanks though.
