### ISSUE TITLE
discussion of inclusion (or not) of webcp

### ISSUE THREAD

**Issue by JedMeister** [DocCyblade/tkl-odoo#21]
I split this off from #19 for specific discussion.

To recap:

> Also @l-arnold I know that you are really keen on your tklwebcp page. I would really like to understand better what you use it for and why. TBH it doesn't really make a lot of sense to me but it's possible I'm missing something...

After having a quick look over the [webroot](https://github.com/DocCyblade/tkl-odoo/tree/dev/overlay/var/www) I note that it looks like there's some pretty detailed documentation that would probably be really useful... Is that why you like having it @l-arnold?

Perhaps we could somehow include that documentation inside Odoo itself instead of on a separate port? Or perhaps we could configure a virtual directory through Apache e.g. /docs or /odoo-docs or something similar... And personally I would still like to get rid of the landing page itself and just have the useful parts of it.

**Comment by JedMeister** [comment]
Also out of curiosity where do those docs come from?

**Comment by l-arnold** [comment]
I need to look again at the Docs.
Some were inside Odoo Git
Some I wrote
Some I googled and found.

A few weeks back right now.  Will follow up on this.
Some of the Docs within the Doc Folder and not really linked from anywhere.  I wrote them on Github.

**Comment by l-arnold** [comment]
I will be back in the AM on this.  Will copy the relavent parts of my other post and put them in here.

Basically trying to make a a more efficient system for the user/participant.

Ideally something like Sphinx or the Git Markup system would help documentation.  I also think there would be a good role for a functional Wiki like system to help with documentation moving forward.

**Comment by JedMeister** [comment]
I sort of like the idea of including documentation but it'd be good to figure out a nice way that we can do it consistently across appliances. In the meantime I'm still inclined to follow the general turnkey convention and just use a docs dir in the root of the git repo (so not in the appliance itself) and also put a copy on the website wiki, under [Appliance specific notes](http://www.turnkeylinux.org/docs/appliances)

Re the WebCP - ok so your motivation is primarily for convenience and reduces your typing. Is that because you use touch devices lots?

To me it would make sense as a landing page. Like if it was on default http/https (80/443) but I couldn't see any real advantage to it on a non-default port. I now see that for you reducing typing is import.

TBH I'm not totally against a landing page with all that info, links etc; I just don't like it on a non-standard port and if it was the landing page of Odoo it'd be nice if it was actually an Odoo page of some sort (from what I gather it's written in Python so should be doable - for a future version...)

Also perhaps another way of looking at it: seeing as you really like it and find it useful then maybe a better way to go would be to devise a script to install it (obviously variations for other appliances). Then you will be able to easily install something similar on all your TurnKey servers. Anyone else that wants to could easily install it too!

**Comment by DocCyblade** [comment]
> Re the WebCP - ok so your motivation is primarily for convenience and reduces your typing. Is that because you use touch devices lots?
> 
> To me it would make sense as a landing page. Like if it was on default http/https (80/443) but I couldn't see any real advantage to it on a non-default port. I now see that for you reducing typing is import.
> 
> TBH I'm not totally against a landing page with all that info, links etc; I just don't like it on a non-standard port and if it was the landing page of Odoo it'd be nice if it was actually an Odoo page of some sort (from what I gather it's written in Python so should be doable - for a future version...)

@JedMeister - I have managed to sneak, ok thats sounds like a bad word, install TKL at work. For the windows guys having a control panel or something web based that tells what the server is does and links to docs IS very helpful in our production environment! 

However, since Odoo is taking over the root URL space the question is where do you put it. At work we a TKL LAPP box that I turned into a web application. I created an virtual directory that /tkl-about-this-server and the webcp is found there, along with documentation specific to that server. It works well, and in other documentation outside of the TKL server I can very easy reference that URL for my co-workers. So maybe that can be an option for Odoo? I will agree with @l-arnold that for folks unlike my self that don't like the command line (them windows folks :smile: ) a web based control panel is very nice. IF we did this, we would need to move Odoo to a /odoo or something like that. Any calls to / would redirect to /odoo Just a thought.

**Comment by DocCyblade** [comment]
Take from #19 

> I am also inclined to remove the apache status mod. It would be better to document that instead IMO.

Also, another thing that is used in production. This time, we have a major software vendor we use for our emergency departments electronic medical record system. This system uses apache as front end servers. The vendor has enabled this on all front end servers for monitoring and health check of each server. So out in the real world this is used, even by a major healthcare vendor. 

Maybe this can be changes to /tkl-about-this-server/web-server-status in line with the above?

**Comment by l-arnold** [comment]
@JedMeister The WebCP SHOULD NOT be the landing page at 80/443.

I would refer to it as the "Admin", or the "Reference" or  simply "Control" page for the Admin.  It is even ok if it were "commonly" turned on or off TBH.

The way Odoo functions, especially with its Front End Web it needs to have Odoo 80/443 be where you come to.

I use Windows but type and use my keyboard almost exclusiely.  This is why my fingers get sore.  I need to Mouse around mainly to CLICK EDIT and CHANGE Port Numbers etc to change from shell to min etc.
The CP is nice becuae it does literally "give me a break" in my normal routine (though I often "right click" anyway to "open as a new tab" the different interfaces.

(Referenced elsewhere, but please see the report from yesterday's hotfix.  It went very very well.  Review  @ https://github.com/DocCyblade/tkl-odoo/issues/13

**Comment by l-arnold** [comment]
re WEBCP:  

From a "pure" TKL consistency issue, I think the main questions I would have are:

1:  Which Port  (12323 might be best rather than 12324 for ssl).  (12325 is simply a HTTP follower and should not be used generally.  I put it there to have a Verification that the server is running if SSL blocks otherwise are insurmountable).  Doing anything if that were truly the situation would require a SSH hook it seems.

2:  What to have on the Top Pane?l

3:  What to have in the index list?

4:  Should this be "installed by default" or "called by a post install script?"

5:  Does it put significant Memory/Processor load on the Server?

6:  Does it expose extra security risks of concern?

I do feel it provides convenience and it would be helpful, to me, to be included in more default aps.

**Comment by l-arnold** [comment]
And in closing:  Odoo itself needs to be 80/443.

I built Openerp 7 on Postgresql app and had the Postgre Landing at 80/443.  It was terrible that way.
This is a control panel but not the Whole Interface.

There could be APP that were builtt for instance,   They might integrat many disparate Sub Domains and were linked together by a Control Panel of this sort.  This normally needs to be interlaced into several web interfaces and is not easy.  Odoo is doing that integration internally (or at least is trying)  

Looking out at the customer and most of the Odoo Users, they need to go to Odoo and will likely never need to go to, or be aware of, the different Ports that could also be visited and accessed.  The WebCP is for that navigation (and as such is primarily Admin based.  

It may actually best be built with a Password Fence in front of it.  Seems it would be a good idea actually.

**Comment by DocCyblade** [comment]
I'll create a experiment branch where we can test using odoo in a virtual directory. Will base it on the final v0.5 tag once it's done.

I am going to go ahead and merge #20 so we can test. We can always bring it back and/or script a gist to customize it as well. Want to try and start testing.

**Comment by DocCyblade** [comment]
As seen in #25 closing comments, had a nice chat with @JedMeister and discussed this for some time. We arrived in agreement that for this base release this will be removed, but with a road map clear of where we would like to see it go the next release. 

The sooner we can get this base install into TKL library, the sooner we can start working on the next release and making this the release that @l-arnold would like to see, as well as my self!

**Comment by l-arnold** [comment]
I'm good with the decision.  Lets move forward!  Thanks to both of you for listening.  I understand the different sides of this and it does save some work right now "making it really worth the mustard".

**Comment by JedMeister** [comment]
:+1: Thanks for your understanding guys. Like Ken noted, I'm open to a landing page, just might want to look at how to best implement it for a future version. :smile:
