### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#24]
Need to figure out what docs to have and where to put the. Right now all docs were moved to .archive

**Comment by DocCyblade** [comment]
Per conversation with @JedMeister, will move any build notes into a `docs/build-notes directory for now. Will come up with a base Readme file with basic info with links to Odoo documentation etc..

**Comment by l-arnold** [comment]
Ok.  Will the readme have hot links or be pure text?

**Comment by l-arnold** [comment]
One Document we should have is 
How to Manually Install an external Module.

It would be nice if we could bring, at least, Git Style formatting to the Odoo Server.  Lets see what is possible.  Ideally it would be something accessible from Webmin actually, so..  lets browse a bit.

It seems Webmin gives a lot of precidence to pure unformatted TEXT files.

**Comment by l-arnold** [comment]
I recommend we have 
openerp-server-man.conf file match openerp-server.conf

except, we should have  "comment" at the begging of the file saying this file is for testing "alternative startup parameters" and needs to be called with the following procedure at startup.

(need to find what that exact proceedure is but I expect something of the sort:

```
 *  ./ openerp-server start -c openerp-server-man.conf
```

**Comment by DocCyblade** [comment]
Basic documentation is done, more detailed docs can be posted on the forums or on the Wiki along with the official release page. I think I have access to submit an edit to that once it is published.

**Comment by l-arnold** [comment]
3rd try now on the build. Usually package download stops.  Will worjbthroughbIbam sure.  Still running so good.

**Comment by l-arnold** [comment]
Sounds good.  Thanks for bringing this together.

Really looking like the main changes for "full features" are the "Add On Page" which seems I could almost Script over an install as well.

I think Carlos went the Patch direction because he could install Odoo over LAPP that way pretty easily.  This is better, but looking forward to being able to throw on Hub Cloud for quick sample runs.
