### ISSUE TITLE
Feature - WebCP on a virtual directory

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#25]
Since Odoo is taking the root/ - Look into having WebCP in a virtual dir say /webcp or tkl-webcp etc..

Need to test that this would not impede odoo as well

**Comment by l-arnold** [comment]
Odoo itself would need to serve the virtual directory.

I think a port like 12323 orv12324 works and is consistent with TKL methods for now.  Could then be used in other aps also.

**Comment by DocCyblade** [comment]
Apache would be doing the work, Odoo would need to be able to be "ok" with having `https://webcp-here/` I think it odoo would be ok with this. I will be testing this out of the experiment branch tonight

**Comment by l-arnold** [comment]
Ok.  I can see lots of value just in finding that out no matter.

Anything I should test now?  Seemed there is a 5 Beta.  Done?  Can I just Pull the Dev Branch to test or should I wait for an assignment again.  (a few windows of time but some travel today too).

**Comment by DocCyblade** [comment]
@l-arnold - If you do a checkout dev-beta-5 that should be the current state of code.

**Comment by DocCyblade** [comment]
After a good chat with Jeremy we agreed that for the first release of TKL Odoo this will not make it. However, we did think if there was a way to use the odoo framework to host it, that would be the way to do it. So it's not gone for good!

Closing this, will open a new issue more specific to adding a landing page using odoo as the framework/module plug in later down the line
