### ISSUE TITLE
Test postfix / odoo integration 

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#29]
Verify emails are being SENT from odoo.

**Comment by l-arnold** [comment]
Worth the Test.  I have seen mails go out of several base TKL Odoo builds.  Was not able to send to my own domain, but sometimes it is the recieving server that is blocking such.  Ideally the MX Record for the Domain will match up with the Odoo Domain being used.  Complicates it I know.

**Comment by DocCyblade** [comment]
I just want verify simple sending. This is kind of the last minute push to tidy things up and look really nice :smile: Want to double check all the little things you know?

**Comment by l-arnold** [comment]
I got the mail. Not sure where it started, but I got the mail. 
Do you need me to check anything specific? It doesn't look like it came from Odoo, but you never know. 

Landis

**Comment by DocCyblade** [comment]
Was able to send email using Odoo and it was in postfix q!
