### ISSUE TITLE
Testing v0.5

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#34]
Any errors or issues post a NEW issues
- [x] Install 
- [x] IP Address (http),  Tranfers automatically to HTTPS
- [x] See that Odoo is running (should land on the Database manager page
- [x] Test "wrong" -ie default password for Database Manager
- [x] Test correct Password - build Sample Database
- [x] Change Admin Password in Odoo Database Manager (testing control)
- [x] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [x] Install CRM Module
- [x] Install Online Billing
- [x] Install Sales Management
- [x]  Create a Customer
- [x]  Create a Quotation for the Customer
- [x]  When quotation is saved, Choose Print  (or Email)
- [x]  See that a Formatted Doc Shows up
- [x]  Ideally see that an Email goes out (should default to Localhost and might work)
- [x]  Check that Git is applying to opt/openerp/odoo files 
- [x] Check manual stop/start/restart work using `/etc/init.d/openerp-server`
- [x] Check manual stop/start/restart work using `systemctl stop openerp-server.service`
  check the status of the service with `systemctl status openerp-server.service`

**Comment by l-arnold** [comment]
Built now.  Will install and test early Sat.  
VM Prepped and ready to run.

Thanks for putting this out!

**Comment by l-arnold** [comment]
Tests Proceeding well.  Takes a long time to create a "demo database"..  Seems longer than before perhaps.

**Comment by l-arnold** [comment]
Will wrap up soon (appointment now) but everything is working so far.

**Comment by DocCyblade** [comment]
What is the specs on the VM how much vRAM and number of vCPUs?

**Comment by l-arnold** [comment]
I use 512mb plus 2 pricesaor as std test.  Run 1 gb production.  

Had to go to 2 gb for jobrunner but not part of current build.  512 should function.

**Comment by l-arnold** [comment]
- re openerp-server start/stop/restart

Ideally the following commands should also work:

cd /opt/openerp
/bin/bash openerp-server stop

It does work from
/etc/init.d
/bin/bash openerp-server stop

Is there a way to have the command also work from /opt/openerp  ?

There is a file there called openerp-server (not seeing what it is just now)

**Comment by l-arnold** [comment]
It appears that each start and stop system needs to generally work in tandem with itself.

If I 
*systemctl stop openerp-server.service
then
*systemctl start openerp-server.service

System comes Up

If I (from anywhere it seems)
- /bin/bash openerp-server stop
  then
  /bin/bash openerp-server start

System comes up

However if I
- /bin/bash openerp-server stop
  then
  *systemctl start openerp-server.service

System does not come up.
I need to use
/bin/bash openerp-server start

I don't actually see this to be a problem although if you want to apply some Extra Proceedures you do need to stop the system with /bin/bash openerp-server (commands)

**Comment by l-arnold** [comment]
Not finding verification of sending mail but I have not configured very much.  I expect it is working find with an external server.

Would still love to know how to make postfix work for incoming and outgoing mail.

I think we are where we need to be with this however.

**Comment by DocCyblade** [comment]
openerp-server is a python script and it is called by the init.d script. It needs to be called with Python and with command line options for the config file

If you look at the init.d script you can see this call

Also you should not need to do /bin/bash just ./

**Comment by l-arnold** [comment]
Ok, I will try some of that.  It did seem in the past I could cycle up and down alternating methods.  I don't think this matters right now however. Mainly curious.

I will browse a bit more.

**Comment by DocCyblade** [comment]
Confirmed that email is sent to postfix.

**Comment by l-arnold** [comment]
Ok.  Seems we can close this.  Any other tests to run?

**Comment by JedMeister** [comment]
@l-arnold 
Just to chime in with a little more info re services. Ideally you should not be running openerp-server directly. If you ever do you should stop the service (daemon) first! Otherwise you will have multiple instances of openerp-server running trying to be the "primary" instance and conflicting with one another. Note that by default the openerp-server will spawn child processes and that's fine; but having multiple parent processes may cause weird random issues...

So for now (until the next major release of Debian at least) the following 3 commands are essentially the same! They all start the odoo 'service'!

```
/etc/initi.d/openerp-server start      # original sysvinit style
service openerp-server start           # newer sysvinit style (also worked for upstart; another init system)
systemctl start openerp-server.service # systemd style command
```

So if you want to use some other commandline options with Odoo (TBH I don't understand why you'd normally need to but that's another story...) then you should stop (`service openerp-server stop` or similar) and then manually run odoo with `/opt/openerp/openerp-server --option` (or whatever the correct path is and whatever options/switches you want to run...
