### ISSUE TITLE
Finite Control of Addons

### ISSUE THREAD

**Issue by l-arnold** [DocCyblade/tkl-odoo#36]
It would be nice to make a simple way to "reach out" into "Addon Space" with odoo and do all the magic of bringing it in to Odoo, including the openerp-server.conf file.

A few ways to do this it seems.  
Putting good controls so that bloat is not created but also that addons can easily be handled would be a great feature.

Will need to work on the "how to" next.

**Comment by DocCyblade** [comment]
Does Odoo or the Odoo community have a web site page or an API that lists all the add on? If there was a list like that we may be able to pull that page and pull the information officer the page and use a script to present them as options.

Was thinking doing this in a similar way but as a static list. If the list would be updated web that would be even better. Don't know what Jeremy would have to say about that.

**Comment by l-arnold** [comment]
This is one Place.  A bit complicated to navigate and not a Git Library as far as I can tell.
It does list quite a spectrum however.

https://apps.openerp.com/apps

**Comment by DocCyblade** [comment]
That's perfect. Could write a special url to grab free ones that are certified that have GIT install

**Comment by l-arnold** [comment]
I will look at this more.
The "certified" thing I believe just means that Odoo made it.  I would not restrict it to that.  That is a whole magnet for pulling folks down the trail towards "Professional Licensing"...  (v. 9 has that going on).

Lets do work on an approach here though for sure.

Landis

**Comment by JedMeister** [comment]
I had a brief look and the certified addons aren't necessarily written/provided by Odoo. They are just ones that Odoo have investigated the code and approved it to run on their managed (SaaS) platform.

A future web scraper (like you suggest @DocCyblade) may be a cool thing for the future. But IMO some lists of useful/suitable addons (inc their dependencies and function) would be a better place to start with this. Providing that link for users to further investigate themselves would be very cool though...

**Comment by DocCyblade** [comment]
I think a start would be to list by certified, by downloads and then remove anything that's already bundled. You can then do another non certified list as well. Take the top 5 of each? How many is too many? 

Or have a way firstboot to pick and choose what to installed

**Comment by l-arnold** [comment]
So far it looks to me like Certified Modules are all in the build right now.

The following is all of the 8.0 Certified Modules and they all look familiar to me.

https://apps.openerp.com/apps/modules/page/4?series=8.0&price=Free&approval=Certified

**Comment by l-arnold** [comment]
Need to look at where the full build comes from.
For instance, this Module was in last night'st (RC1) build.
https://apps.openerp.com/apps/modules/8.0/auth_dynamic_groups/

I do not see it as being "certified" and yet it is in our build.

Coming in under /OCA/Servertools

Very Strange that this is listing as I do not see any /OCA/ Downloads at all.  The original Database I believe was built in the "DocCyBlade" realm -- not with the larger list of modules at "L-Arnold".

**Comment by l-arnold** [comment]
One Module I do not see in our build but listed as Certified is:

https://apps.openerp.com/apps/modules/8.0/website_less/
git@github.com:odoo/design-themes.git#8.0
Another is:
https://apps.openerp.com/apps/modules/8.0/snippet_latest_posts/
git@github.com:odoo/design-themes.git#8.0

Both are generically referred to as "Design Themes"  and seem to be in the same GIT Repository, so might have something to do with the issue.

**Comment by DocCyblade** [comment]
Close this, see #37 as it will cover this
