### ISSUE TITLE
Target Shutdown sometimes does not complete

### ISSUE THREAD

**Issue by l-arnold** [DocCyblade/tkl-odoo#51]
This just happened to me on an older Beta 1.0 Build and Last Nights Dev-RC1 Build.

From Conf Console, choose Shutdown and shutdown starts but does not complete.

Ends with "reached target shutdown".  Need to issue VM specific - Power Off to complete.

On Dev-RC1 happened right after applying a Static IP address.

**Comment by DocCyblade** [comment]
I confirmed this. I think this is a TKL issue. As it does the same thing with core but only after a change in the network

**Comment by DocCyblade** [comment]
It seems it only happens on first boot? I can't replicate the issue after a reboot.

**Comment by l-arnold** [comment]
I will close.  Correct, seems a TKL issue and has been reported in Tracker.

**Comment by JedMeister** [comment]
This should have been fixed in RC3 IIRC. Even then it should only ever happen after initial install. 

FWIW it was because it was waiting for the CD to be ejected. ANd it would wait forever. We changed it so that it auto ejected the CD and then waited briefly before continuing. We never tested on a physical machine but on a VM it should just "eject" the ISO and reboot...

**Comment by l-arnold** [comment]
This was not in the "install loop" but perhaps after an install when the machine was not "rebooted".  It is quite odd.  Sometimes it seems it happens to old machine installs too but not clear really.

(Separate subject) The "wait for the CD" eject does have a VMWARE dialog come up as you note during the Install Reboot loop itself for sure..  If there, I need choose "no" then the system reboots.  

That however is not what I am referring to.  This was a "shutdown command" from ConfConsole.  Happened to a few builds today.

**Comment by JedMeister** [comment]
Hmmm. That's really weird... It sounds like a similar issue but slightly different. TBH I'm not too worried about it ATM. We'll have to look into it further though at some point.
