### ISSUE TITLE
Kens Shakedown tests part 1

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#52]
Going to use this to document my shake down testing  of RC1

Test will be done with VMWare Fusion with
1 X CPU
1GB RAM
20GB HDD

Test one will install all modules available and test each one using CRUD and every option at least 3 times. 

Goal is to test all modules and options with limited resources. Will note any issues here. If issue is with resources will note that and retest in part 2

Keep list of things tested here only. Add comments if any issues only.

Test List:
- [ ] ISO Live Preview (Basic new database and module) **Fails** with 512MB RAM would need 1GB
- [X] ISO Install Guided Setup all
- [X] ISO Install Guided Setup LVM (Defaults)
- [X] First Boot: Signup for email alerts
- [X] First Boot: Updates
- [X] Create new database
- [X] Update Company Info
- [X] Add two users
- [X] Delete user
- [X] Install and configure all local modules
- [X] Test Modules (Basic function of each)
- [X] CRM
- [X] Social Network
- [X] Online Billing
- [X] Point of Sale
- [X] Project Management
- [X] Notes
- [X] Issue Tracking
- [X] Accounting and Finance
- [X] Survey
- [X] Sales Management
- [X] Warehouse Management
- [X] Instant Messaging
- [X] MRP
- [X] Purchase Management
- [X] Employee Directory
- [X] Timesheets
- [X] Recruitment Process
- [X] Leave Management
- [X] Expense Tracker
- [X] Employee Appraisals
- [X] Calendar
- [X] Address Book
- [X] Gamification
- [X] Live Chat
- [X] Odoo Live Support
- [X] Lunch Orders
- [X] Website Builder
- [X] Blogs
- [X] Online Events
- [X] Forum
- [X] eCommerce
- [X] Fleet Management

**Comment by DocCyblade** [comment]
Test List:

   - [ ] Item 1

**Comment by DocCyblade** [comment]
Half way through the installing of modules the server froze and ran out of memory. 512MB not enough may need to bump it up to 1GB

**Comment by DocCyblade** [comment]
I found that changing the max memory soft value to 268435456 (256MB) seem to calm the memory usage. This number should not be more than 1/4 of your memory on your system. Seems like if this number if too high the worker processes never quit and release memory, eating it up till it locks up

**Comment by DocCyblade** [comment]
Should come up with some matrix for memory to workers equation or at least best setting to whatever the final TKL VM will have for memory

**Comment by DocCyblade** [comment]
Installed all modules, had to tweak the max_memory_soft above

<img width="1179" alt="screen shot 2015-10-15 at 11 17 49 pm" src="https://cloud.githubusercontent.com/assets/9731860/10533109/2fae31a8-7393-11e5-9a41-bd6796425f83.png">

<img width="1206" alt="screen shot 2015-10-15 at 11 18 00 pm" src="https://cloud.githubusercontent.com/assets/9731860/10533113/34c4a51e-7393-11e5-972e-d0208928078c.png">

<img width="1440" alt="screen shot 2015-10-15 at 11 18 13 pm" src="https://cloud.githubusercontent.com/assets/9731860/10533115/3cffd7e4-7393-11e5-8f94-ea42f24bee5a.png">

**Comment by l-arnold** [comment]
What is your math on the "number" and mb/gb etc?  I had tried to calc 1.5 Gig myself earlier but came out with the different number I mentioned earlier.  Also this doesn't seem to correlate to bits or kilobits either.

**Comment by DocCyblade** [comment]
I take 256MB and punch it into here
http://www.whatsabyte.com/P1/byteconverter.htm

**Comment by DocCyblade** [comment]
Been playing around with the tuning of 512MB RAM with all modules installed. System is VERY slow but it does work. If they are using only 2-3 modules this would be "ok" but ideal. I did tweak the max_memory_soft to 128MB and max_memory_hard to 1.3G anything less than 1.3G PDF reports would not work. I tried bumping the workers to 1 but things started timing out. You could put this to one, and bump up soft memory limit or bump up the time outs on cpu/time but i think the below settings are "ok" for 512MB if thats all you had. I am thinking that 1GB really should be the minimum, as you can see it's eating into swap

See below screen shots of config and memory usage.

<img width="1416" alt="screen shot 2015-10-16 at 6 03 24 am" src="https://cloud.githubusercontent.com/assets/9731860/10539452/a5ad165a-73cd-11e5-9db3-cd955af6ebe6.png">

<img width="1439" alt="screen shot 2015-10-16 at 6 14 33 am" src="https://cloud.githubusercontent.com/assets/9731860/10539454/aa4a6bb8-73cd-11e5-8faa-ab5f932b4aaf.png">

**Comment by DocCyblade** [comment]
Note on above post, i have not rebooted just restarted Odoo. Below shot after reboot. Still high memory usage and we have not done anything yet

<img width="1440" alt="screen shot 2015-10-16 at 6 23 36 am" src="https://cloud.githubusercontent.com/assets/9731860/10539595/8fe62d7e-73ce-11e5-89bc-60fd7d3a3d59.png">

**Comment by l-arnold** [comment]
Ok, will fire up.  What is the command to seebthe memory usage?

**Comment by DocCyblade** [comment]
top

I then use commands to make that screen. Use h for help

Need to run it at the console

**Comment by JedMeister** [comment]
`top` is good; `htop` is prettier and has cool bar graphs :smile:

**Comment by DocCyblade** [comment]
Is htop in the build ? Or do you add it?

**Comment by JedMeister** [comment]
I install it from the repos. It's only a 200kb

BTW you guys are stress testing the shiz outta this thing! :smile:

**Comment by DocCyblade** [comment]
@JedMeister if anything I have learned is the memory management and the scaling of the app.

Ill have to install htop

**Comment by DocCyblade** [comment]
@JedMeister dude what are you still doing up? Don't you sleep!

Yeah want to put my stamp of approval on it it's going to be almost perfect

**Comment by l-arnold** [comment]
Logging into shell:  20 GB hd, 4gb Ram, 2 Processors
and after setting Soft Limit to 256mb and Hard Limit to 3GB
I see:
https://192.168.1.115:12321/
HD usage at 11.7%
Memory Usage at 17 %
124 Processes running

Just ran:  apt-get install htop
htop Jumps.  Pretty cool.

**Comment by DocCyblade** [comment]
@JedMeister - Testing is going very well. Only thing I have found is performance issues with 512MB if you go all crazy town and do what I did and install 20| modules

**Comment by DocCyblade** [comment]
I am done with part 1

**Comment by l-arnold** [comment]
Nice work Ken.

Don't do what I did and Get Tired in Crazy town and install 12 Modules all at once
:smile:
