### ISSUE TITLE
Kens Shakedown tests part 2

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#54]
Going to use this to document my shake down testing of RC1 part 2

Test will be done with VMWare Fusion with
2 X CPU
4GB RAM
20GB HDD

Test will be done with DEMO data 

Test one will install all modules available and test each one using CRUD and every option at least 3 times. 

Goal is to test all modules and options with limited resources. Will note any issues here. 

Retest anything that failed due to resources again here 

 Once testing is done, add two more databases with all modules, for a total of three databases. Report on any issues with multi databases and the functionalities of them

Keep list of things tested here only. Add comments if any issues only.
- [X] ISO Live Preview (Basic new database and module)
- [X] ISO Install Guided Setup all
- [X] ISO Install Guided Setup LVM (Defaults)
- [X] First Boot: Signup for email alerts
- [X] First Boot: Updates
- [X] Create new database
- [X] Update Company Info
- [X] Add two users
- [X] Delete user
- [X] Install and configure all local modules
- [ ] Test Modules (Basic function of each)
- [X] CRM
- [X] Social Network
- [X] Online Billing
- [X] Point of Sale
- [X] Project Management
- [X] Notes
- [X] Issue Tracking
- [X] Accounting and Finance
- [X] Survey
- [X] Sales Management
- [X] Warehouse Management
- [X] Instant Messaging
- [X] MRP
- [X] Purchase Management
- [X] Employee Directory
- [X] Timesheets
- [X] Recruitment Process
- [X] Leave Management
- [X] Expense Tracker
- [X] Employee Appraisals
- [X] Calendar
- [X] Address Book
- [X] Gamification
- [X] Live Chat
- [X] Odoo Live Support
- [X] Lunch Orders
- [X] Website Builder
- [X] Blogs
- [X] Online Events
- [X] Forum
- [X] eCommerce
- [X] Fleet Management

**Comment by l-arnold** [comment]
Explain CRUD.

"All Modules" is about 400 Modules.

I think best is to do "realistic" Tests for Small Business first.  Many Modules can be added on but normally a "multitude"is not added on.  Will work on this.
Not sure I have 4 GB available..  Let me see.

**Comment by DocCyblade** [comment]
All installed modules in RC1 

Not EVERY module out there. I saw only 15 or so installed in RC1

**Comment by DocCyblade** [comment]
Create / Read / Update / Delete 

Means that if you can add something edit something and delete something then try and do it.

**Comment by DocCyblade** [comment]
If you don't have 4GB then As much as you can test.

**Comment by l-arnold** [comment]
Ok.  My Methodology will be to Create some critical Snapshots.  
Install Reboot
Sales Management

then I will put some big Modules in and maybe go back after to a different big module.

Will see if I can get 3 Gb.  Maybe 4 if I turn a few VM's off for a bit.

**Comment by l-arnold** [comment]
Going to close this one, keep mis posting.

**Comment by DocCyblade** [comment]
Odoo runs much better with 4G and 2 x cpu - Will need to work out a worker process and memory for a 4GB install because you could run out of memory here as well

**Comment by DocCyblade** [comment]
The Live CD works basic install of a few modules ram being used is 1.4GB have not changed memory config at all so this could come down a bit

**Comment by DocCyblade** [comment]
Pretty much done with my testing, bottom line most things work fine. more memory is better and we need to tweak memory settings in conf file for whatever we land on the VM memory size
