### ISSUE TITLE
ERROR: Google Calendar Module on install

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#56]
Google Calendar Module gave an Error on installation

Warning, Each Constraint Module must be unique

**Comment by DocCyblade** [comment]
@l-arnold - Did you get this on a basic install or the 4GB install? Do you remember what memory conf tweaks you did. Want to try an replicate this

**Comment by l-arnold** [comment]
Yes,  4 gb Ram, Memory Set high.
Again, likely something in the Odoo Setup.  Likely was trying to throw a field into the database and the field was already there..  That or somethng related.  I will Install Google Calendar early on my next test to see if any issues appear.  I don't work with Google Hooks like this and generally I don't think it is "specifically" core to Odoo, but it is getting loaded in the base install.  There are several other components we could test Like "OAUTH" etc...  but again those are generally config issues.

**Comment by DocCyblade** [comment]
Looks like its an odoo demo data issue. Not related to TKL build
