### ISSUE TITLE
ERROR: ValidateError on process payment

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#57]
made Invoice. Went to process payment: Odoo Error:

ValidateError

Field(s) currency_id failed against a constraint: The selected account of your Journal Entry forces to provide a secondary currency. You should remove the secondary currency on the account or select a multi-currency view on the journal.

**Comment by DocCyblade** [comment]
@l-arnold - Did you get this on a basic install or the 4GB install? Do you remember what memory conf tweaks you did. Want to try an replicate this

**Comment by l-arnold** [comment]
Something wrong in the Odoo Demo Data.  Not really our problem.  Likely having to do with EURO or Dollar possiblity and how that particular Payment System was set up.

I say we don't worry about that issue right now.  Totally ODOO centric.  Not based on RAM etc (yes 4gb Ram, 2 Processors)  Memory Set High.

**Comment by DocCyblade** [comment]
Closing this per above

**Comment by l-arnold** [comment]
Did install with No errors on Second Database actually running less Ram.

I think it is an issue of Data running into Data.  I had installed less modules when I installed Google Calendar the second time.
