### ISSUE TITLE
ERROR: Live Preview locks up

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#59]
ISO Live Preview (Basic new database and module) **Fails** with 512MB RAM

Not really a bug but want to log this and document this anyway. Not sure what TKL Devs think about this

**Comment by DocCyblade** [comment]
https://github.com/DocCyblade/tkl-odoo/issues/54#issuecomment-148849530 - Able to get this working

**Comment by DocCyblade** [comment]
@JedMeister - Thoughts on this? Its not an issue with TKL but Odoo is very resource hungry and if there is small ram it won't run very nicely. Can you disable the live boot?

**Comment by l-arnold** [comment]
I personally am not worried about "Live Preview".  If someone loads with 512 we can warn them.  It did run for me reasonably well with 1 processor and 1 gb.

**Comment by JedMeister** [comment]
Live only works from ISO and you can't control ISO install RAM (from the installer) anyway. I suspect that 512 is not enough to run live because it also has the whole OS loaded in RAM & no swap...

**Comment by l-arnold** [comment]
It did run for me with 512mb.  Thr purpose isbjustvto preview and conf console had the cool option ogbinstallingvstraight from the preview.

Certainly recomending morebram would make sense.

**Comment by l-arnold** [comment]
Hate this phone keyboard.

"B" = "space"

**Comment by DocCyblade** [comment]
Going to close this, as it does "work" but you need some real horsepower to run it correctly. May want to just document this
