### ISSUE TITLE
User Mail is sent but not Redirected Transaction Mail

### ISSUE THREAD

**Issue by l-arnold** [DocCyblade/tkl-odoo#60]
I just created 2 users with 2 email addresses I have.

Both recieved Password reset instructions.

I just went to send an order email and did not yet receive to one of those addresses.

An Odoo Issue but would be nice to know the quick debug on it.

**Comment by DocCyblade** [comment]
I think this is due to the email server. I assume Odoo is delivering email to the localhost postfix app. It's up to postfix to deliver it to another smtp server or dump it to a relay to be sent. May be something that documented? Is there documentation out there for email settings for odoo?

**Comment by l-arnold** [comment]
Email is complicated.  I need to see if I have documented sufficiently.
Have set up 2 perhaps 3 systems where Email functioned properly.

Issues having to do w/ crossing Spam Filters are real ones.
Email addresses need to line up properly etc etc.

I think we are good for now on this.
