### ISSUE TITLE
Final Test: v14-READY - KR

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#62]
Final Test: Ken's Results:

I changed the workers to 0 this puts it into threaded mode. We need to test the following and document real memory and swap space used just to make sure this will work in most situations.
#### Final Testing Checklist
- [X] Build ISO from dev-14-ready
- [X] CPU x 1  / 512MB RAM
  - [X] Instal from ISO
  - [X] Create new database with DEMO Data
  - [X] Install Sales Management App
  - [X] Print 4 items at a time (Should download PDF)
  - [X] Note Real Memory Usage: 457MB of 480MB
  - [X] Note Swap Memory Usage: 5MB of 509MB
- [X] CPU x 2  / 512MB RAM
  - [X] Instal from ISO
  - [X] Create new database with DEMO Data
  - [X] Install Sales Management App
  - [X] Print 4 items at a time (Should download PDF)
  - [X] Note Real Memory Usage: 458MB of 480MB
  - [X] Note Swap Memory Usage: 10MB of 509MB
- [X] CPU x 1  / 1GB RAM
  - [X] Instal from ISO
  - [X] Create new database with DEMO Data
  - [X] Install Sales Management  App
  - [X] Print 4 items at a time (Should download PDF)
  - [X] Note Real Memory Usage: 653MB of 986MB
  - [X] Note Swap Memory Usage: 1021MB of 0MB
- [X] CPU x 2  / 2GB RAM
  - [X] Instal from ISO
  - [X] Create new database with DEMO Data
  - [X] Install Sales Management  App
  - [X] Print 4 items at a time (Should download PDF)
  - [X] Note Real Memory Usage: 632MB of 1996MB
  - [X] Note Swap Memory Usage: 0MB of 2044MB
- [X] CPU x 2  / 4GB RAM
  - [X] Instal from ISO
  - [X] Create new database with DEMO Data
  - [X] Install Sales Management  App
  - [X] Print 4 items at a time (Should download PDF)
  - [X] Note Real Memory Usage: 651MB of 3952MB
  - [X] Note Swap Memory Usage: 0MB of 493MB

**Comment by DocCyblade** [comment]
As a side note, was able to get a snap shot of the PDF process, note the VIRT, yeah thats 1.2GB. Got me wondering as I don't even have that much memory to start. So I looked up TOPs man page and found this

```
VIRT  --  Virtual Memory Size (KiB)
           The total amount of virtual memory used by the task.  It includes
           all code, data and shared libraries plus pages that have been
           swapped out and pages that have been mapped but not used.
```

So that makes sense why the limit_memory_hard has to be set so high, yet works.

<img width="1440" alt="screen shot 2015-10-17 at 10 02 03 pm" src="https://cloud.githubusercontent.com/assets/9731860/10562170/7e4f1578-751b-11e5-9d2d-5e397345d408.png">

**Comment by JedMeister** [comment]
Nice detective work @DocCyblade :+1:

**Comment by DocCyblade** [comment]
Complete!
