### ISSUE TITLE
Test Beta 4

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-odoo#7]
Testing Beta 4
Keep this post check boxes only. If you find any errors don't post them here add a new issue and prefix it with `[v0.4] -`
- [x] Install 

required:  /bin/bash openerp-server restart command (not sure if needs to be folder specifid)
then could create database, change admin password etc.
- [x] See that Odoo is running (should land on the Database manager page
- [x] Change Admin Password in Odoo Database Manager (testing control)
- [x] install new database with new password
  worth check that openerp-server.con admin-db variable also changes  -- sometimes Odoo can "cache" this but not change it if not writing to openerp-server.conf properly
- [x] Install CRM Module
- [x] Install Online Billing
- [x] Install Sales Management

Go to Settings/Users
- give Admin "technical settings" checkbox
- make "sales manager" in user rights/sales
- [x]  Create a Customer
- [x]  Create a Quotation for the Customer
- [x]  When quotation is saved, Choose Print  (or Email)
-  Got The error below related to wkhtmltox:
- [ ]  See that a Formatted Doc Shows up
- [ ]  Ideally see that an Email goes out (should default to Localhost and might work)
- [x]  Check that Git is applying to opt/openerp/odoo files 
- Git Branch returns 8.0 in /opt/openerp/odoo/

**Comment by DocCyblade** [comment]
After you finish v0.3 give this a spin, if you are already on the DEV branch you should be able to just `git pull` command then re-run make. Make sure `git log`  shows the beta 4 merge. This should fix the startup issue where Odoo is not working.

**Comment by l-arnold** [comment]
Buildt 4.0.  Writes Odoo Admin Passwod but Access Denied in Database manager so cannot proceed.

I see the password was set in etc/odoo/openerp-server.conf.  However cannot create a database or change the password within Odoo Database Manager.  Odoo database manager does come up however.  Perhaps there is a different .conf file that it is using/creating ??

Traceback (most recent call last):
  File "/opt/openerp/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/openerp/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/openerp/odoo/openerp/http.py", line 311, in _call_function
    return self.endpoint(_args, **kwargs)
  File "/opt/openerp/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/openerp/odoo/addons/web/controllers/main.py", line 704, in create
    params['create_admin_pwd'])
  File "/opt/openerp/odoo/openerp/http.py", line 879, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/openerp/odoo/openerp/http.py", line 115, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/openerp/odoo/openerp/service/db.py", line 65, in dispatch
    security.check_super(passwd)
  File "/opt/openerp/odoo/openerp/service/security.py", line 32, in check_super
    raise openerp.exceptions.AccessDenied()
AccessDenied: Access denied.

**Comment by l-arnold** [comment]
went to
/etc/init.d/

ran command
/bin/bash/openerp-server restart

and was able to create a database.  Expect I can change the Password as well
CONFIRMED:  Could then also change the Password.  IT does change it properly also in /etc/odoo/openerp-server.conf

We NEED TO HAVE a BACKUP File be created after first INITHOOKS, as ODOO reformats the full FILE.  

My opinion anyway.

Working generally in a good way if we can have that /bin/bash openerp-server restart command take place in firstboot inithook finish process.

**Comment by l-arnold** [comment]
wkhtmltopdf/wkhtmltox error  (we need wkhtmltox)

Report (PDF)

Wkhtmltopdf failed (error code: -6). Message: The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --footer-html, is not support using unpatched qt, and will be ignored.QXcbConnection: Could not connect to display

**Comment by l-arnold** [comment]
I do not recall what dependencies wkhtmltox has.  I do know that one or two of the font packages are involved.

**Comment by DocCyblade** [comment]
Awesome feed back

**Comment by DocCyblade** [comment]
@l-arnold can you open issues for each problem? Some of these would span both 3-4, that would also keep the comments for each issue in its own discussion

**Comment by l-arnold** [comment]
OK, can do so though actually the nature of most of the problems changed between generations.

Will put wkhtmltox out there as I know we have that one.

**Comment by DocCyblade** [comment]
We can tag issues with a version number

**Comment by l-arnold** [comment]
Moved to HotFix Issue
