### ISSUE TITLE
logo should have transparent background

### ISSUE THREAD

**Issue by JedMeister** [DocCyblade/tkl-odoo#70]
currently the [odoo logo](https://github.com/turnkeylinux-apps/odoo/blob/master/.art/logo.png) has a white background - it should be transparent.

**Comment by DocCyblade** [comment]
Are these requirements for release?

**Comment by JedMeister** [comment]
No this doesn't block; just should be done at some point (the website currently has white background).

But needs to not be forgotten.

BTW it's a nice looking logo! :smile: :+1:

**Comment by DocCyblade** [comment]
@l-arnold I think you made the logos right? Think you can create an alpha channel so that the logo is transparent?

**Comment by l-arnold** [comment]
I will follow with this.  Need to look at the built set but should be able to get that transparent.  If not someone tell me the command (haven't used the "Alpha Channel" descriptor for transparent before but I do know what, where and why it should be used.

**Comment by DocCyblade** [comment]
Ok do some testing on it. If your doc-dev branch is up to date with mine you can branch off of that make your changes and do a PR between that branch and the dev.

Any questions just send up a signal flare

**Comment by l-arnold** [comment]
Ok,  Will get to this hopefully this evening.  Big project just now I can't quite put down yet.

**Comment by JedMeister** [comment]
No rush on this guys; although like I say we need to make sure we don't forget it...

You guys probably already know but there are some [gimp templates](https://github.com/turnkeylinux/artwork/tree/master/templates) in the [artwork repo](https://github.com/turnkeylinux/artwork). I suspect that they probably won't be useful at this late stage but still wanted to make sure you were aware of them...

**Comment by l-arnold** [comment]
I'm not a subscriber or a believer, but I have and I learned Photoshop well enough that I am sticking with it for now. 
I did download Gimp  (need to do so again).  Wasn't quite on board with how it worked last time around.  Had to build a new computer since then so its not in this time around yet.
Photoshop is great, just can be damned expensive.    I do act like a luddite though and don't upgrade much and I definitely don't subscribe.  (CS4/CS2 is my universe right now)

**Comment by JedMeister** [comment]
That's fine Landis. No problem with using whichever tool works best for you.

**Comment by l-arnold** [comment]
I forgot a bit how to Post an external File:

![logo](https://cloud.githubusercontent.com/assets/5673448/10865720/fbdbb914-7fda-11e5-84c8-6fb9aaa170f7.png)

This should be transparaent instead of white.  Thinking I need to FTP it in then recommit.

**Comment by l-arnold** [comment]
![logo - alpha](https://cloud.githubusercontent.com/assets/5673448/11131640/d90c3ba8-8948-11e5-9420-454487c7c683.png)

This one I selected "convert to alpha" to the selection that had been white and alternatively transparent earlier.  I will also email to you Jeremy.

Let me know if this works.
Thanks,
Landis

**Comment by l-arnold** [comment]
I think we are good with this one.
