### ISSUE TITLE
Plans for Odoo 9

### ISSUE THREAD

**Issue by jackrabb1t** [DocCyblade/tkl-odoo#72]
Hi

i was looking for your roadmap to support odoo 9.

**Comment by l-arnold** [comment]
Itcseems that Odoobis moving away from Open Source.  The license changed between 8.0 and 9.0.

We should study this but my opinion is that it is beat to focus on veraion 8.0.

I do thonk it might be worth making a veraion 7,0 veraion as it removes the Web Publishingvside which hasbsone advantages.

Tricky subject.  Let-s discuss more.

**Comment by l-arnold** [comment]
It aeems that Odoo is moving away from Open Source.  The license changed between 8.0 and 9.0.

We should study this but my opinion is that it is best to focus on veraion 8.0.

I do thonk it might be worth making a veraion 7,0 veraion as it removes the Web Publishingvside which hasbsone advantages.

Tricky subject.  Let-s discuss more.

**Comment by l-arnold** [comment]
Sorrg for the typos on my phone..  Will delete when I hit a laptop.

It seems that Odoo is moving away from Open Source.  The license changed between 8.0 and 9.0.

We should study this but my opinion is that it is best to focus on veraion 8.0.

I do thonk it might be worth making a veraion 7,0 veraion as it removes the Web Publishingvside which hasbsone advantages.

Tricky subject.  Let-s discuss more.

**Comment by jackrabb1t** [comment]
Odoo 9 is LGPL 
https://www.odoo.com/page/legal

A clearer description of the license transition - http://www.camptocamp.com/en/actualite/odoo-9-community-and-enterprise-editions-a-renewed-open-source-model/

However, the feature comparison between the community versions of v8 and v9 - not clear.

**Comment by DocCyblade** [comment]
I think we will stick with v8 for now. I have not touched v9 source so I can't say about the features. I am closing this for now but it will be on the radar for sure. It took a lot of work just to get v8 in TKL!
