### ISSUE TITLE
wkhtmltox installation

### ISSUE THREAD

**Issue by l-arnold** [DocCyblade/tkl-odoo#9]
In my experience w/ Odoo 8 we have to install wkhtmltox outside of package management.  Not able to render an email or print an order etc as of beta 3 and beta 4.

**Comment by DocCyblade** [comment]
Was able to confirm this, working on importing the needed files

**Comment by l-arnold** [comment]
in the TKL Forums back when I was first Implementing wkhtmltox I noted the following requirements.  I recall also loading a few other dpi Fonts later as well (ie 150).  These load as packages or python pulls it seems.

libjpeg-turbo8
xfonts-base
xfonts-75dpi

---

noted this needs to go "before" wkhtmltox

apt-get install xfonts-base

**Comment by DocCyblade** [comment]
Just found that out! Saw the install failed due to missing depends

**Comment by l-arnold** [comment]
Also, note using the ODOO directory rather than "gna.org" who seem to be keeping wkhtmltopdf and its derivatives.  Should help against using the myriad of wrong versions.  (NOTE 2.1 not 1.2 on Odoo get above)  Odoo SHOULD KNOW HOWEVER!

wget http://nightly.odoo.com/extra/wkhtmltox-0.12.1.2_linux-jessie-amd64.deb

vs.
Source: http://wkhtmltopdf.org/downloads.html  goes to:  
http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb

ARCH=amd64
REL=jessie
GEN=0.12
VER=0.12.2.1
 wget http://download.gna.org/wkhtmltopdf/${GEN}/${VER}/wkhtmltox-${VER}_linux-${REL}-${ARCH}.deb

**Comment by l-arnold** [comment]
Seems an Open Issue for them:  12.1.2 (from Odoo) would be preferred to 12.2.1 from wkhtmltopdf
ref:
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2156

**Comment by l-arnold** [comment]
I knew I learned it somewhere.  Strange, very little docs on the subject.  Thanks though for verifying.

**Comment by JedMeister** [comment]
Nice work guys! Totally happy with that! :+1:

**Comment by DocCyblade** [comment]
Fixed with v0.4.1

**Comment by DocCyblade** [comment]
Regarding the limit_memory_hard option and why it seems to need at least 1.3G see https://github.com/DocCyblade/tkl-odoo/issues/62#issuecomment-148968899
